#!/usr/bin/perl

sub err404
{
	#Utiliser la page par défaut 404
	print CLIENT "HTTP/1.1 404 Not Found\r\n" .
            	     "Content-Type: text/html\r\n" .
                     "Content-Length: " . length($default) . "\r\n\r\n" .
                    $default;
               
        #writelog
    	close CLIENT;
    	exit 0;
}
